### ISSUE TITLE
Player's Search

### ISSUE THREAD

**Issue by Hochmah** [zakaihamilton/screens#3]
Hi Zakai,

The Player's search is not working properly. When I typer an term, I always get "No Match Found". And sometimes the result list is showing html tags as well.

![image](https://user-images.githubusercontent.com/20425869/55105022-514a5880-50aa-11e9-975a-5492b3268f5c.png)
![image](https://user-images.githubusercontent.com/20425869/55105058-67581900-50aa-11e9-8752-08700127b0ba.png)

**Comment by zakaihamilton** [comment]
I fixed it
